### ISSUE TITLE
codec/whoosh3.py:1116: SyntaxWarning: "is" with a literal. Did you mean "=="?

### ISSUE THREAD

**Issue by pkolmann** [mchaput/whoosh#20]
Hi,

we stumbled across this issue after updating to Debian Bullseye and I see it is still in this repo:

https://github.com/mchaput/whoosh/blob/5421f1ab3bb802114105b3181b7ce4f44ad7d0bb/src/whoosh/codec/whoosh3.py#L1120

shouldn't that be
`elif fixedsize == 0:`

Thanks
Philipp

**Comment by gioboske** [comment]
I think this is closed by d9a3fa2.

**Comment by pkolmann** [comment]
Thanks for fixing.
